-- Products
INSERT OR REPLACE INTO products (id, name, version, description, download_url, price, currency, status, client_name, created_at, updated_at) VALUES (1, 'Test', '1', 'Test script', 'https://example.com/download/test', 0, 'USD', 'active', 'Main Admin', '2025-09-24 04:08:27', '2025-09-24 04:08:27');
INSERT OR REPLACE INTO products (id, name, version, description, download_url, price, currency, status, client_name, created_at, updated_at) VALUES (2, 'test', '1', 'test', 'https://example.com/download/test', 0, 'USD', 'active', 'Main Admin', '2025-09-24 04:08:41', '2025-09-24 04:08:41');
INSERT OR REPLACE INTO products (id, name, version, description, download_url, price, currency, status, client_name, created_at, updated_at) VALUES (3, 'Professional Suite', '2.1.0', 'Advanced business automation software with premium features', 'https://example.com/downloads/pro-suite-v2.1.exe', 199.99, 'USD', 'active', 'Main Admin', '2025-09-28 02:34:56', '2025-09-28 02:34:56');
INSERT OR REPLACE INTO products (id, name, version, description, download_url, price, currency, status, client_name, created_at, updated_at) VALUES (4, 'Security Guard Enterprise', '1.5.2', 'Enterprise-grade security and monitoring solution', 'https://example.com/downloads/security-guard.exe', 499.99, 'USD', 'active', 'Main Admin', '2025-09-28 02:34:56', '2025-09-28 02:34:56');
INSERT OR REPLACE INTO products (id, name, version, description, download_url, price, currency, status, client_name, created_at, updated_at) VALUES (5, 'Development Tools Pro', '3.0.1', 'Professional development toolkit for software developers', 'https://example.com/downloads/dev-tools.exe', 299.99, 'USD', 'inactive', 'Main Admin', '2025-09-28 02:34:56', '2025-10-01 14:37:31');
INSERT OR REPLACE INTO products (id, name, version, description, download_url, price, currency, status, client_name, created_at, updated_at) VALUES (7, 'Professional Suite', '2.1.0', 'Advanced business automation software', 'https://example.com/downloads/pro-suite.exe', 199.99, 'USD', 'active', 'Main Admin', '2025-09-28 06:53:37', '2025-09-28 06:53:37');

-- Customers
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (1, 'Alice Johnson', 'alice@example.com', 1, 'ABCD-EFGH-IJKL-MNOP');
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (2, 'Bob Smith', 'bob@techcorp.com', 2, 'QRST-UVWX-YZAB-CDEF');
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (3, 'Carol Davis', 'carol@startup.io', 1, 'GHIJ-KLMN-OPQR-STUV');
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (4, 'David Wilson', 'david@consulting.net', 3, 'WXYZ-1234-5678-9ABC');
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (5, 'Eva Martinez', 'eva@designstudio.com', 4, 'DEFG-HIJK-LMNO-PQRS');
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (6, 'Frank Thompson', 'frank@enterprise.org', 2, 'TUVW-XYZA-BCDE-FGHI');
INSERT OR REPLACE INTO customers (id, name, email, product_id, license_key) VALUES (7, 'Demo Customer', 'demo@example.com', 1, 'DEMO-1234-5678-9ABC');

-- License Rules
INSERT OR REPLACE INTO license_rules (id, name, description, max_activations, max_concurrent_sessions, max_days, grace_period_days, max_devices, max_ips, allow_vm, allowed_countries, blocked_countries, timezone_restrictions, allow_offline_days, require_periodic_validation, validation_interval_hours, is_active, created_at, updated_at) VALUES (1, 'Standard License', 'Basic license for individual users with standard features', 0, 2, 365, 7, 3, 0, 0, '["US", "CA", "GB", "AU"]', '', '', 7, 1, 24, 1, '2025-09-28 02:34:56', '2025-09-28 02:34:56');
INSERT OR REPLACE INTO license_rules (id, name, description, max_activations, max_concurrent_sessions, max_days, grace_period_days, max_devices, max_ips, allow_vm, allowed_countries, blocked_countries, timezone_restrictions, allow_offline_days, require_periodic_validation, validation_interval_hours, is_active, created_at, updated_at) VALUES (2, 'Premium License', 'Enhanced license with premium features and extended support', 0, 5, 365, 7, 10, 0, 0, '[]', '', '', 30, 1, 24, 1, '2025-09-28 02:34:56', '2025-09-28 02:34:56');
INSERT OR REPLACE INTO license_rules (id, name, description, max_activations, max_concurrent_sessions, max_days, grace_period_days, max_devices, max_ips, allow_vm, allowed_countries, blocked_countries, timezone_restrictions, allow_offline_days, require_periodic_validation, validation_interval_hours, is_active, created_at, updated_at) VALUES (3, 'Enterprise License', 'Full-featured license for enterprise customers', 0, 20, 730, 7, 50, 0, 0, '[]', '', '', 90, 1, 24, 1, '2025-09-28 02:34:56', '2025-09-28 02:34:56');
INSERT OR REPLACE INTO license_rules (id, name, description, max_activations, max_concurrent_sessions, max_days, grace_period_days, max_devices, max_ips, allow_vm, allowed_countries, blocked_countries, timezone_restrictions, allow_offline_days, require_periodic_validation, validation_interval_hours, is_active, created_at, updated_at) VALUES (4, 'Trial License', 'Limited trial license for evaluation purposes', 0, 1, 30, 7, 1, 0, 0, '["US", "CA", "GB"]', '', '', 1, 1, 24, 1, '2025-09-28 02:34:56', '2025-09-28 02:34:56');
INSERT OR REPLACE INTO license_rules (id, name, description, max_activations, max_concurrent_sessions, max_days, grace_period_days, max_devices, max_ips, allow_vm, allowed_countries, blocked_countries, timezone_restrictions, allow_offline_days, require_periodic_validation, validation_interval_hours, is_active, created_at, updated_at) VALUES (5, 'Geographic Restricted', 'License restricted to specific geographic regions', 0, 3, 365, 7, 5, 0, 0, '["US", "CA"]', '', '', 14, 1, 24, 1, '2025-09-28 02:34:56', '2025-09-28 02:34:56');
